# For cross-compiling from Linux to Windows x86 using mingw32
# http://www.mingw.org/
#
# $ make SYSTEM=opensuse-mingw32
#

include config/Makefile.linux-mingw32

CC    := i686-w64-mingw32-gcc
LD    := i686-w64-mingw32-ld
LDFLAGS.GL += -L/usr/i686-w64-mingw32/sys-root/mingw/lib
